---

- hosts: all
  gather_facts: false
  tasks:
    - name: echo a
      debug: msg={{ a | default('undefined')}}
    - name: echo b
      debug: msg={{ b | default('undefined') }}
    - name: echo c
      debug: msg={{ c | default('undefined') }}
    - name: echo d
      debug: msg={{ d | default('undefined') }}
