- name: Inspect elements of directory being ran inside of
  connection: local
  hosts: all
  gather_facts: no
  tasks:
    - shell: pwd
      run_once: true
      register: pwd_cmd

    - name: print files in current directory
      run_once: true
      debug: msg="{{ pwd_cmd.stdout_lines[0] }}"

    - set_fact:
        tower_dir: "{{ lookup('env','AWX_PRIVATE_DATA_DIR') }}"

    - name: print private directory, msg is the tower private dir here
      debug: msg="{{ tower_dir }}"

    - shell: ls -p {{ tower_dir }}/*
      run_once: true
      register: list_cmd

    - name: print filenames of all files (will exclude non-tmp files)
      debug: msg="{{ list_cmd.stdout_lines }}"

    - name: save list of all files that start with "tmp"
      shell: ls -p {{ tower_dir }}/tmp*
      run_once: true
      register: list_cmd

    - name: print contents of all files
      debug: msg="{{ item }}"
      with_file: "{{ list_cmd.stdout_lines }}"
