---
- hosts: localhost
  connection: local
  # Use like
  # ansible-playbook -i localhost, large_stats.yml -e "{count: 9}"
  tasks:
  - set_stats:
      data:
        mai_list: "[{% for number in range(count) %}'foooooooooooooooooo', {% endfor %}]"